In [1]:
import pandas as pd
import matplotlib.pyplot as plt

plt.style.use('ggplot')

In [2]:
df = pd.read_csv("data.csv")
df.head()

,Index,batting_team,bowling_team,city,runs_left,balls_left,wickets,target_runs,cur_run_rate,req_run_rate,result
0,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,119,10,208,6.0,10.43697479,0
1,1,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,118,10,208,3.0,10.52542373,0
2,2,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,117,10,208,2.0,10.61538462,0
3,3,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,205,116,10,208,4.5,10.60344828,0
4,4,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,201,115,10,208,8.4,10.48695652,0

In [3]:
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72413 entries, 0 to 72412
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         72413 non-null  int64
 1   batting_team  72413 non-null  object
 2   bowling_team  72413 non-null  object
 3   city          71581 non-null  object
 4   runs_left     72413 non-null  int64
 5   balls_left    72413 non-null  int64
 6   wickets       72413 non-null  int64
 7   target_runs   72413 non-null  int64
 8   cur_run_rate  72413 non-null  float64
 9   req_run_rate  72408 non-null  object
 10  result        72413 non-null  int64
dtypes: float64(1), int64(6), object(4)
memory usage: 6.1+ MB

,Index,runs_left,balls_left,wickets,target_runs,cur_run_rate,result
count,72413.000000,72413.000000,72413.000000,72413.000000,72413.000000,72413.000000,72413.000000
mean,36206.000000,93.258379,62.657078,7.535967,166.583956,7.439523,0.525624
std,20903.976858,50.021962,33.404593,2.138637,29.282200,2.275850,0.499346
min,0.000000,-15.000000,-2.000000,0.000000,66.000000,0.000000,0.000000
25%,18103.000000,54.000000,35.000000,6.000000,147.000000,6.257143,0.000000
50%,36206.000000,93.000000,63.000000,8.000000,166.000000,7.480519,1.000000
75%,54309.000000,131.000000,92.000000,9.000000,186.000000,8.682353,1.000000
max,72412.000000,250.000000,119.000000,10.000000,251.000000,42.000000,1.000000